#!/usr/bin/env python3
"""Import paper summaries from a JSONL file into Neon.

This is most useful for ingesting summaries generated by ``multi_prompt`` in
``--jsonl {path}`` mode, which is what we do for local LLM inference servers
(VSCode port-forwarding can be brittle or drop large payloads).

Usage:
    uv run python import_jsonl.py results.jsonl
    uv run python import_jsonl.py results.jsonl --dry-run     # preview without writing
    uv run python import_jsonl.py results.jsonl --save-md     # also save markdown files to docs/
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from loguru import logger

from neon_db import NeonDB

# Columns we accept on the JSONL import path. ``arxiv_id`` is required and is
# passed positionally to ``NeonDB.save_paper``.
_WRITABLE_FIELDS: tuple[str, ...] = ("title", "category", "pitch", "summary", "url")

_FILENAME_TITLE_LIMIT: int = 80
_MAX_FILENAME_SUFFIX_ATTEMPTS: int = 1000


def _record_fields(record: dict[str, Any]) -> dict[str, Any]:
    """Extract only the columns NeonDB.save_paper knows about.

    Falls back to empty strings for missing keys so import stays idempotent
    with existing JSONL files.
    """
    return {key: record.get(key, "") for key in _WRITABLE_FIELDS}


def _unique_output_path(category_dir: Path, base_name: str) -> Path:
    candidate = category_dir / base_name
    if not candidate.exists():
        return candidate
    stem = candidate.stem
    suffix = candidate.suffix
    for k in range(2, _MAX_FILENAME_SUFFIX_ATTEMPTS):
        alt = category_dir / f"{stem}-{k}{suffix}"
        if not alt.exists():
            return alt
    raise RuntimeError(f"Could not find a free filename under {category_dir} for {base_name}")


def save_markdown(record: dict[str, Any]) -> Path:
    """Write a paper record as a markdown file under ``docs/<category>/``."""
    category = record.get("category") or "uncategorized"
    category_dir = Path("docs") / category
    category_dir.mkdir(parents=True, exist_ok=True)

    arxiv_id = record["arxiv_id"]
    title = record.get("title") or ""
    norm = re.sub(r"[^A-Za-z0-9._-]+", "-", title).strip("-")[:_FILENAME_TITLE_LIMIT]
    base_name = f"{arxiv_id}-{norm}.md" if norm else f"{arxiv_id}.md"
    output_file = _unique_output_path(category_dir, base_name)

    arxiv_link = f"\n**ArXiv:** [{arxiv_id}](https://arxiv.org/abs/{arxiv_id})\n"
    content = f"# {title}\n{arxiv_link}\n## Pitch\n\n{record.get('pitch', '')}\n\n---\n\n{record.get('summary', '')}\n"
    output_file.write_text(content)
    return output_file


def _load_records(jsonl_path: Path) -> list[dict[str, Any]]:
    """Parse a JSONL file, skipping blank lines and reporting decode errors."""
    records: list[dict[str, Any]] = []
    for lineno, raw in enumerate(jsonl_path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            logger.warning("Skipping line {}: {}", lineno, exc)
    return records


def _preview(records: list[dict[str, Any]]) -> None:
    for r in records:
        summary_len = len(r.get("summary", ""))
        logger.info(
            "  {:15s}  {:25s}  {}  ({} chars)",
            str(r.get("arxiv_id", "?")),
            str(r.get("category", "?")),
            str(r.get("title", "?"))[:60],
            summary_len,
        )
    logger.info("Dry run: {} records would be imported", len(records))


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Import JSONL paper summaries into Neon")
    parser.add_argument("jsonl_file", help="Path to JSONL file to import")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview records without writing to Neon",
    )
    parser.add_argument(
        "--save-md",
        action="store_true",
        help="Also save markdown files to docs/",
    )
    return parser


def main() -> None:
    args = _build_parser().parse_args()

    jsonl_path = Path(args.jsonl_file)
    if not jsonl_path.exists():
        logger.error("File not found: {}", jsonl_path)
        sys.exit(1)

    records = _load_records(jsonl_path)
    logger.info("Found {} records in {}", len(records), jsonl_path)

    if args.dry_run:
        _preview(records)
        return

    db = NeonDB()
    db.init_schema()

    imported = 0
    for r in records:
        arxiv_id = r.get("arxiv_id")
        if not arxiv_id:
            logger.warning("Skipping record without arxiv_id: {}", r)
            continue

        db.save_paper(arxiv_id, **_record_fields(r))
        imported += 1

        if args.save_md:
            md_path = save_markdown(r)
            logger.info("  {} -> Neon + {}", arxiv_id, md_path)
        else:
            logger.info("  {} -> Neon", arxiv_id)

    logger.success("Imported {} papers into Neon", imported)


if __name__ == "__main__":
    main()
