#!/usr/bin/env python3
"""Import paper summaries from a JSONL file into the local papers.db.
This is most useful for import summaries generated by script like multi_prompt in --jsonl {path_to_jsonl file} mode
Which is suitable for local LLM inference servers, since VSCode port forwarding can be brittle / drop large paylods
or have inconsistent behaviour.
Usage:
    python import_jsonl.py results.jsonl
    python import_jsonl.py results.jsonl --dry-run     # preview without writing
    python import_jsonl.py results.jsonl --save-md      # also save markdown files to docs/
"""

import argparse
import json
import sqlite3
import sys
from pathlib import Path

from database import DB_PATH, _migrate_sync


def import_to_db(record: dict, con: sqlite3.Connection) -> None:
    """Insert or update a single paper record."""
    con.execute(
        """
        INSERT INTO papers (id, title, category, pitch, summary, url)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            title = excluded.title,
            category = excluded.category,
            pitch = excluded.pitch,
            summary = excluded.summary,
            url = excluded.url
        """,
        (
            record["arxiv_id"],
            record.get("title", ""),
            record.get("category", ""),
            record.get("pitch", ""),
            record.get("summary", ""),
            record.get("url", ""),
        ),
    )


def save_markdown(record: dict) -> Path:
    """Save a paper record as a markdown file under docs/<category>/."""
    import re

    category = record.get("category", "uncategorized")
    category_dir = Path("docs") / category
    category_dir.mkdir(parents=True, exist_ok=True)

    arxiv_id = record["arxiv_id"]
    title = record.get("title", "")
    # Normalize title for filename
    norm = re.sub(r"[^A-Za-z0-9._-]+", "-", title).strip("-")[:80]
    base_name = f"{arxiv_id}-{norm}.md" if norm else f"{arxiv_id}.md"
    output_file = category_dir / base_name

    if output_file.exists():
        stem, suffix = output_file.stem, output_file.suffix
        for k in range(2, 1000):
            candidate = category_dir / f"{stem}-{k}{suffix}"
            if not candidate.exists():
                output_file = candidate
                break

    arxiv_link = f"\n**ArXiv:** [{arxiv_id}](https://arxiv.org/abs/{arxiv_id})\n"
    content = f"# {title}\n{arxiv_link}\n## Pitch\n\n{record.get('pitch', '')}\n\n---\n\n{record.get('summary', '')}\n"
    output_file.write_text(content)
    return output_file


def main():
    parser = argparse.ArgumentParser(description="Import JSONL paper summaries into papers.db")
    parser.add_argument("jsonl_file", help="Path to JSONL file to import")
    parser.add_argument("--dry-run", action="store_true", help="Preview records without writing to DB")
    parser.add_argument("--save-md", action="store_true", help="Also save markdown files to docs/")
    args = parser.parse_args()

    jsonl_path = Path(args.jsonl_file)
    if not jsonl_path.exists():
        print(f"Error: {jsonl_path} not found", file=sys.stderr)
        sys.exit(1)

    records = []
    for i, line in enumerate(jsonl_path.read_text().splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Warning: skipping line {i}: {e}", file=sys.stderr)

    print(f"Found {len(records)} records in {jsonl_path}")

    if args.dry_run:
        for r in records:
            summary_len = len(r.get("summary", ""))
            print(f"  {r['arxiv_id']:15s}  {r.get('category', '?'):25s}  {r.get('title', '?')[:60]}  ({summary_len} chars)")
        print(f"\nDry run: {len(records)} records would be imported")
        return

    _migrate_sync()
    con = sqlite3.connect(DB_PATH)
    imported = 0
    for r in records:
        if "arxiv_id" not in r:
            print(f"Warning: skipping record without arxiv_id: {r}", file=sys.stderr)
            continue
        import_to_db(r, con)
        imported += 1
        if args.save_md:
            md_path = save_markdown(r)
            print(f"  {r['arxiv_id']} -> DB + {md_path}")
        else:
            print(f"  {r['arxiv_id']} -> DB")

    con.commit()
    con.close()
    print(f"\nImported {imported} papers into {DB_PATH}")


if __name__ == "__main__":
    main()
