import React, { useMemo, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  Pressable,
  StyleSheet,
  Linking,
  ActivityIndicator,
} from 'react-native';
import { useLocalSearchParams, useNavigation, useRouter } from 'expo-router';
import { getPaper, getAdjacentPapers, getRelatedPapers, graph } from '../../../lib/graph';
import { recordOpened, isRead, markRead, unmarkRead } from '../../../lib/db';
import { useReadState } from '../../../hooks/useReadState';
import type { Paper } from '../../../lib/types';

// Markdown rendering — react-native-enriched-markdown
// Note: requires dev build (not compatible with Expo Go)
let MarkdownRenderer: React.ComponentType<{ children: string }> | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const mod = require('react-native-enriched-markdown');
  MarkdownRenderer = mod.Markdown ?? mod.default ?? null;
} catch {
  MarkdownRenderer = null;
}

// Build-time bundle of paper content
// Papers are bundled via Metro's static asset system.
// The content map is generated by scripts/build-graph.mjs into assets/papers/.
function getPaperContent(category: string, slug: string): string {
  // In a production build, paper content would be loaded from bundled assets.
  // For now, return the pitch/abstract as a minimal body since full MD files
  // are not yet copied to assets/papers/. See mobile/BLOCKERS.md for setup.
  const paper = getPaper(category, slug);
  if (!paper) return '# Paper not found';

  const lines = [
    `# ${paper.title}`,
    '',
    paper.arxivId ? `**ArXiv:** [${paper.arxivId}](https://arxiv.org/abs/${paper.arxivId})` : '',
    '',
    paper.pitch ? `## Summary\n\n${paper.pitch}` : '',
    '',
    paper.organization ? `**Organization:** ${paper.organization}` : '',
    paper.authors ? `**Authors:** ${(JSON.parse(paper.authors as unknown as string) as string[]).slice(0, 5).join(', ')}` : '',
    '',
    '---',
    '',
    `*Full paper body not yet bundled. Open the ArXiv link above to read the complete paper.*`,
    '',
    paper.arxivId ? `[Open on ArXiv](https://arxiv.org/abs/${paper.arxivId})` : '',
  ].filter((l) => l !== undefined);

  return lines.join('\n');
}

export default function PaperDetailScreen() {
  const { category, slug } = useLocalSearchParams<{ category: string; slug: string }>();
  const navigation = useNavigation();
  const router = useRouter();

  const paper = useMemo(
    () => (category && slug ? getPaper(category, slug) : undefined),
    [category, slug]
  );

  const { read, toggle: toggleRead } = useReadState(paper?.id ?? '');
  const catMeta = paper ? graph.categories[paper.category] : undefined;

  const { prev, next } = useMemo(
    () => (paper ? getAdjacentPapers(paper) : { prev: null, next: null }),
    [paper]
  );
  const related = useMemo(() => (paper ? getRelatedPapers(paper) : []), [paper]);

  // Record open + update header title
  useEffect(() => {
    if (paper) {
      recordOpened(paper.id);
      navigation.setOptions({ title: paper.title.slice(0, 40) + (paper.title.length > 40 ? '…' : '') });
    }
  }, [paper, navigation]);

  if (!paper) {
    return (
      <View style={styles.error}>
        <Text style={styles.errorText}>Paper not found</Text>
      </View>
    );
  }

  const accentColor = catMeta?.color ?? '#aa99ff';
  const content = getPaperContent(paper.category, paper.slug);

  const openArxiv = () => {
    if (paper.arxivId) {
      Linking.openURL(`https://arxiv.org/abs/${paper.arxivId}`);
    }
  };

  const openGithub = () => {
    if (paper.github) {
      Linking.openURL(paper.github);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Category pill */}
      <Pressable
        style={[styles.catPill, { backgroundColor: accentColor + '22' }]}
        onPress={() => router.push(`/c/${paper.category}` as never)}
      >
        <Text style={[styles.catPillText, { color: accentColor }]}>
          {catMeta?.title ?? paper.category}
        </Text>
      </Pressable>

      {/* Title */}
      <Text style={styles.title}>{paper.title}</Text>

      {/* Meta row */}
      <View style={styles.metaRow}>
        <Text style={styles.meta}>{paper.year}</Text>
        {paper.month && <Text style={styles.meta}>• {paper.month.toString().padStart(2, '0')}</Text>}
        <Text style={styles.meta}>• {paper.readTimeMin} min read</Text>
        {paper.wordCount && <Text style={styles.meta}>• {paper.wordCount.toLocaleString()} words</Text>}
      </View>

      {/* Organization / score row */}
      <View style={styles.metaRow}>
        {paper.organization && <Text style={styles.org}>{paper.organization}</Text>}
        {paper.score != null && (
          <View style={[styles.scorePill, { backgroundColor: accentColor + '22' }]}>
            <Text style={[styles.scoreText, { color: accentColor }]}>★ {paper.score}/10</Text>
          </View>
        )}
        {paper.upvotes != null && (
          <Text style={styles.meta}>↑ {paper.upvotes}</Text>
        )}
      </View>

      {/* Action buttons */}
      <View style={styles.actions}>
        <Pressable
          style={[styles.actionBtn, { backgroundColor: read ? '#00E599' + '22' : '#2a2a2a' }]}
          onPress={toggleRead}
        >
          <Text style={[styles.actionBtnText, { color: read ? '#00E599' : '#ffffff' }]}>
            {read ? '✓ Marked Read' : 'Mark as Read'}
          </Text>
        </Pressable>

        {paper.arxivId && (
          <Pressable style={styles.actionBtnSecondary} onPress={openArxiv}>
            <Text style={styles.actionBtnSecondaryText}>ArXiv ↗</Text>
          </Pressable>
        )}

        {paper.github && (
          <Pressable style={styles.actionBtnSecondary} onPress={openGithub}>
            <Text style={styles.actionBtnSecondaryText}>GitHub ↗</Text>
          </Pressable>
        )}
      </View>

      {/* Paper body */}
      <View style={styles.body}>
        {MarkdownRenderer ? (
          <MarkdownRenderer>{content}</MarkdownRenderer>
        ) : (
          <PlainTextFallback content={content} />
        )}
      </View>

      {/* Topics */}
      {paper.topics.length > 0 && (
        <View style={styles.topicsSection}>
          <Text style={styles.relatedTitle}>Topics</Text>
          <View style={styles.topicChips}>
            {paper.topics.map((t) => (
              <Pressable
                key={t}
                style={styles.topicChip}
                onPress={() => router.push(`/topic/${t}` as never)}
              >
                <Text style={styles.topicChipText}>{t}</Text>
              </Pressable>
            ))}
          </View>
        </View>
      )}

      {/* Related papers */}
      {related.length > 0 && (
        <View style={styles.relatedSection}>
          <Text style={styles.relatedTitle}>Related Papers</Text>
          {related.slice(0, 4).map((rp) => (
            <Pressable
              key={rp.id}
              style={styles.relatedItem}
              onPress={() => router.push(`/p/${rp.category}/${rp.slug}` as never)}
            >
              <Text style={[styles.relatedCat, { color: graph.categories[rp.category]?.color ?? '#aa99ff' }]}>
                {graph.categories[rp.category]?.title ?? rp.category}
              </Text>
              <Text style={styles.relatedItemTitle} numberOfLines={2}>{rp.title}</Text>
            </Pressable>
          ))}
        </View>
      )}

      {/* Prev / Next navigation */}
      <View style={styles.navRow}>
        {prev && (
          <Pressable
            style={[styles.navBtn, styles.navBtnLeft]}
            onPress={() => router.push(`/p/${prev.category}/${prev.slug}` as never)}
          >
            <Text style={styles.navBtnLabel}>← Older</Text>
            <Text style={styles.navBtnTitle} numberOfLines={1}>{prev.title}</Text>
          </Pressable>
        )}
        {next && (
          <Pressable
            style={[styles.navBtn, styles.navBtnRight]}
            onPress={() => router.push(`/p/${next.category}/${next.slug}` as never)}
          >
            <Text style={styles.navBtnLabel}>Newer →</Text>
            <Text style={styles.navBtnTitle} numberOfLines={1}>{next.title}</Text>
          </Pressable>
        )}
      </View>
    </ScrollView>
  );
}

function PlainTextFallback({ content }: { content: string }) {
  // Split content into paragraphs and render with basic styling
  const lines = content.split('\n');
  return (
    <View style={{ gap: 8 }}>
      {lines.map((line, i) => {
        if (line.startsWith('# ')) {
          return <Text key={i} style={plain.h1}>{line.slice(2)}</Text>;
        }
        if (line.startsWith('## ')) {
          return <Text key={i} style={plain.h2}>{line.slice(3)}</Text>;
        }
        if (line.startsWith('### ')) {
          return <Text key={i} style={plain.h3}>{line.slice(4)}</Text>;
        }
        if (line.startsWith('**') && line.endsWith('**')) {
          return <Text key={i} style={plain.bold}>{line.slice(2, -2)}</Text>;
        }
        if (line.startsWith('---')) {
          return <View key={i} style={plain.divider} />;
        }
        if (!line.trim()) {
          return <View key={i} style={{ height: 8 }} />;
        }
        return <Text key={i} style={plain.body}>{line}</Text>;
      })}
    </View>
  );
}

const plain = StyleSheet.create({
  h1: { fontSize: 22, fontWeight: '700', color: '#ffffff', marginTop: 8 },
  h2: { fontSize: 18, fontWeight: '700', color: '#e0e0e0', marginTop: 16 },
  h3: { fontSize: 16, fontWeight: '600', color: '#c0c0c0', marginTop: 12 },
  bold: { fontSize: 15, fontWeight: '600', color: '#ffffff' },
  body: { fontSize: 15, color: '#c0c0c0', lineHeight: 24 },
  divider: { height: 1, backgroundColor: '#2a2a2a', marginVertical: 12 },
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  content: {
    padding: 16,
    paddingBottom: 60,
    gap: 12,
  },
  catPill: {
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  catPillText: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 30,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexWrap: 'wrap',
  },
  meta: {
    fontSize: 13,
    color: '#666666',
  },
  org: {
    fontSize: 13,
    color: '#a0a0a0',
    flex: 1,
  },
  scorePill: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  scoreText: {
    fontSize: 12,
    fontWeight: '600',
  },
  actions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  actionBtn: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '600',
  },
  actionBtnSecondary: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  actionBtnSecondaryText: {
    fontSize: 14,
    color: '#a0a0a0',
    fontWeight: '500',
  },
  body: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#2a2a2a',
  },
  topicsSection: {
    gap: 8,
    marginTop: 8,
  },
  relatedTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  topicChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  topicChip: {
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  topicChipText: {
    fontSize: 12,
    color: '#a0a0a0',
  },
  relatedSection: {
    gap: 8,
    marginTop: 8,
  },
  relatedItem: {
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  relatedCat: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  relatedItemTitle: {
    fontSize: 14,
    color: '#ffffff',
    lineHeight: 20,
  },
  navRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  navBtn: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  navBtnLeft: {},
  navBtnRight: {
    alignItems: 'flex-end',
  },
  navBtnLabel: {
    fontSize: 11,
    color: '#666666',
    textTransform: 'uppercase',
  },
  navBtnTitle: {
    fontSize: 13,
    color: '#ffffff',
  },
  error: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a0a0a',
  },
  errorText: {
    color: '#666666',
    fontSize: 16,
  },
});
